server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://ms-discovery-server.cfapps.io

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
    
  jpa:
    generate-ddl: true
